services:
  db:
    image: postgres:17.4-alpine3.21
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
    networks:
      - net_inner
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrator:
    build:
      context: ./app
    command: ["-m", "alembic", "upgrade", "head"]
    restart: on-failure
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db/db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app/:/usr/src/app/
    networks:
      - net_inner

  tester:
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    command: [ "test_main.py" ]
    restart: on-failure
    environment:
      LOAD_FAKE_DATA: 1
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    volumes:
      - ./app/:/usr/src/app/
    networks:
      - net_inner

  app:
    build:
      context: ./app
    command: ["main.py"]
    restart: always
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    ports:
      - '8000:8000'
    volumes:
      - ./app/:/usr/src/app/
    networks:
      - net_inner

networks:
  net_inner:
    name: betty
    driver: bridge
